---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: acme-clothing-api
  namespace: acme-clothing-microstaging-4242
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-01f5726e0a68f24b6,subnet-03b0d4de6cdf50bb3,subnet-048642c9b828e6f23
    alb.ingress.kubernetes.io/tags: ManagedBy=Blocklayer,blocklayer_pipeline=acme-clothing-microstaging-4242
spec:
  rules:
    - host: api.acme-clothing-microstaging-4242.infralabs.io
      http:
        paths:
          - path: /*
            backend:
              serviceName: acme-clothing-api
              servicePort: api-port
