name: Blocklayer Pipeline Cleanup

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: master
      - name: Cleanup Blocklayer environment
        uses: blocklayerhq/actions@alpha-2
        with:
          entrypoint: ./.github/.github-pr-close.sh
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          api_key: "${{ secrets.BL_API_KEY }}"
          pipeline: "acme-clothing-pr-${PR_NUMBER}"
