name: Blocklayer

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Blocklayer webhook integration
        uses: blocklayerhq/actions@alpha-3-ingest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          bl_api_key: "${{ secrets.BL_API_KEY }}"
          bl_domain : "acme.infralabs.io"
          bl_target : "env.devInfra.input.monorepoEvents"
