name: Blocklayer

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with Blocklayer
        uses: blocklayerhq/actions@alpha-2
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          api_key: "${{ secrets.BL_API_KEY }}"
          pipeline: "acme-clothing-pr-${PR_NUMBER}"
          workspace: acme-corp
          clone: acme-clothing-staging
          inputs: -w acme-corp -o name=acme-clothing-pr-${PR_NUMBER} -o git_ref=${{ github.sha }}
