name: Blocklayer

on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Deploy with Blocklayer
        uses: blocklayerhq/actions@alpha-3-push
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          bl_api_key: "${{ secrets.BL_API_KEY }}"
          bl_domain : "acme.infralabs.io"
          bl_target : "env.devInfra.config.monorepo"
